services:
  web:
    build: .
    container_name: django_gunicorn_teamC
    volumes:
      - ./src:/app
      - static_volume:/usr/share/nginx/html/static/  # 追加
    ports:
      - "8003:8003"
    depends_on:
      - db
      - nginx
  db:
    image: mysql:8.0.28
    container_name: mysql_db_teamC
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: o-hara_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: o-hara
    volumes:
      - db_data:/var/lib/mysql
  nginx:
    image: nginx:1.21.1
    container_name: nginx_server_teamC
    ports:
      - "83:83"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/share/nginx/html/static  # 追加
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    container_name: phpmyadmin_teamC
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8083:83"
    depends_on:
      - db

volumes:
  db_data:
  static_volume:  # 追加
