# Generated by Django 4.2 on 2023-11-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='updated_date',
            field=models.DateField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
