# Generated by Django 4.2 on 2024-01-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.TextField(max_length=1050, verbose_name='内容'),
        ),
    ]
