# Generated by Django 4.2 on 2023-12-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='counseling',
            field=models.BooleanField(default=False, verbose_name='カウンセリング可否'),
        ),
    ]
