# Generated by Django 4.2 on 2023-11-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_week_ai_month_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week_ai',
            name='created_date',
            field=models.DateField(verbose_name='作成日時'),
        ),
    ]
