# Generated by Django 4.2 on 2024-01-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary_counseling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='counseling',
            field=models.IntegerField(default=0, verbose_name='カウンセリング可否'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='created_date',
            field=models.DateField(verbose_name='作成日時'),
        ),
    ]
