# Generated by Django 4.2 on 2023-11-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_week_ai_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month_ai',
            name='created_date',
            field=models.DateField(verbose_name='作成日時'),
        ),
    ]
