# Generated by Django 4.2 on 2024-01-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diary_counseling_alter_diary_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='created_date',
            field=models.DateField(verbose_name='作成日時'),
        ),
    ]
