# Generated by Django 4.2 on 2024-01-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_emotion_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='diary',
            name='created_date',
            field=models.DateField(null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='created_date',
            field=models.DateField(null=True, verbose_name='作成日時'),
        ),
    ]
